// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ULDS","status":true,"description":"无限图层显示系统 (内附详细教程)","parameters":{"Default Path":"parallaxes","Default Z":"0.5"}},
{"name":"RegionPassage","status":true,"description":"区域通行","parameters":{"Passable Regions":"[\"0\"]","Impassable Regions":"[\"255\"]"}}
];
